// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProxyEndpoint() {
  return window['go']['main']['App']['GetProxyEndpoint']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTunSettings() {
  return window['go']['main']['App']['GetTunSettings']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function PingAll() {
  return window['go']['main']['App']['PingAll']();
}

export function PingServer(arg1) {
  return window['go']['main']['App']['PingServer'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetProxySettings(arg1) {
  return window['go']['main']['App']['SetProxySettings'](arg1);
}

export function SetTunSettings(arg1) {
  return window['go']['main']['App']['SetTunSettings'](arg1);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
