// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function AddServer(arg1:model.ServerProfile):Promise<model.ServerProfile>;

export function Connect(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAutostart():Promise<boolean>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetProxyEndpoint():Promise<string>;

export function GetProxySettings():Promise<model.ProxySettings>;

export function GetServers():Promise<Array<model.ServerProfile>>;

export function GetStatus():Promise<main.ConnStatus>;

export function GetTunSettings():Promise<model.TunSettings>;

export function HideToTray():Promise<void>;

export function IsAdmin():Promise<boolean>;

export function ListProcesses():Promise<Array<string>>;

export function PingAll():Promise<void>;

export function PingServer(arg1:string):Promise<main.PingResult>;

export function QuitApp():Promise<void>;

export function RestartAsAdmin():Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetProxySettings(arg1:model.ProxySettings):Promise<void>;

export function SetTunSettings(arg1:model.TunSettings):Promise<void>;

export function UpdateServer(arg1:model.ServerProfile):Promise<void>;
